// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Feb 21 11:29:26 2012

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef SETHOMEPAGEDIALOG_H
#define SETHOMEPAGEDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

class CDBAccess;

class SetHomepageDialog: public wxDialog {
private:
    static const wxString PAGE_DEFAULT;
    static const wxString PAGE_LINGOSHOOK_DOWNLOAD;
    static const wxString PAGE_LINGOSHOOK_BLOG;
public:
    // begin wxGlade: SetHomepageDialog::ids
    // end wxGlade

    SetHomepageDialog(CDBAccess* dbaccess, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: SetHomepageDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: SetHomepageDialog::attributes
    wxStaticText* label_1;
    wxComboBox* m_listHomepage;
    wxStaticLine* static_line_2;
    wxButton* m_btnOK;
    wxPanel* panel_1;
    wxButton* m_btnCancel;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnListText(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnOK(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnCancel(wxCommandEvent &event); // wxGlade: <event_handler>
private:
    void InitHomepageList();
    int SetHomepage(const wxString& page);
private:
    CDBAccess* _objDBAccess;
}; // wxGlade: end class


#endif // SETHOMEPAGEDIALOG_H
