// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Mar 01 14:10:32 2011

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef XMLGENERATOR_H
#define XMLGENERATOR_H


// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
protected:
    static const wxString XMLFILE_NAME;
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStaticText* label_1;
    wxTextCtrl* m_textDonator;
    wxStaticText* label_2;
    wxTextCtrl* m_textDate;
    wxStaticText* label_3;
    wxTextCtrl* m_textOutput;
    wxStaticLine* static_line_1;
    wxStaticText* label_4;
    wxTextCtrl* m_textPlugin;
    wxStaticText* label_5;
    wxTextCtrl* m_text7zip;
    wxStaticText* label_6;
    wxTextCtrl* m_textOpenssl;
    wxStaticLine* static_line_2;
    wxButton* m_btnGenerate;
    wxPanel* panel_1;
    wxButton* button_2;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtnGenerate(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
private:
    int Generate(const wxString& donator, const wxString& date, const wxString& output) const;
    int Zip(const wxString& output, const wxString& plugin, const wxString& zip) const;
    int Check(const wxString& output, const wxString& openssl) const;
}; // wxGlade: end class


#endif // XMLGENERATOR_H
