// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug 09 11:06:41 2010

#include "ConfigData.h"

#include "AnalysisFilterSettingDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



CAnalysisFilterDialog::CAnalysisFilterDialog(const CConfigData* conf, wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
, _config(conf)
{
    // begin wxGlade: CAnalysisFilterDialog::CAnalysisFilterDialog
    sizer_1_staticbox = new wxStaticBox(this, -1, wxEmptyString);
    m_cbCase = new wxCheckBox(this, wxID_ANY, _("Case Insensitive"));
    m_cbOneWordEachDict = new wxCheckBox(this, wxID_ANY, _("One word in each dictionary"));
    m_cbOneWordAllDict = new wxCheckBox(this, wxID_ANY, _("One word in all dictionaries"));
    static_line_1 = new wxStaticLine(this, wxID_ANY);
    button_1 = new wxButton(this, wxID_CANCEL, _("Cancel"));
    panel_1 = new wxPanel(this, wxID_ANY);
    button_2 = new wxButton(this, wxID_OK, _("OK"));

    set_properties();
    do_layout();
    // end wxGlade
}


void CAnalysisFilterDialog::set_properties()
{
    // begin wxGlade: CAnalysisFilterDialog::set_properties
    SetTitle(_("Analysis Filter Setting.."));

    m_cbCase->SetValue(_config->m_iAFCaseInsensitive == 1);
    m_cbOneWordEachDict->SetValue(_config->m_iAFOneWordEachDict == 1);
    m_cbOneWordAllDict->SetValue(_config->m_iAFOneWordAllDict == 1);
    // end wxGlade
}


void CAnalysisFilterDialog::do_layout()
{
    // begin wxGlade: CAnalysisFilterDialog::do_layout
    wxStaticBoxSizer* sizer_1 = new wxStaticBoxSizer(sizer_1_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    sizer_2->Add(m_cbCase, 0, wxALL, 4);
    sizer_2->Add(m_cbOneWordEachDict, 0, wxALL, 4);
    sizer_2->Add(m_cbOneWordAllDict, 0, wxALL, 4);
    sizer_1->Add(sizer_2, 1, wxEXPAND, 0);
    sizer_1->Add(static_line_1, 0, wxALL|wxEXPAND, 8);
    sizer_3->Add(button_1, 0, 0, 0);
    sizer_3->Add(panel_1, 1, wxEXPAND, 0);
    sizer_3->Add(button_2, 0, 0, 0);
    sizer_1->Add(sizer_3, 0, wxALL|wxEXPAND, 8);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

