// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 22 15:39:22 2010

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef TAGINPUTDIALOG_H
#define TAGINPUTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade


class TagInputDialog: public wxDialog {
public:
    // begin wxGlade: TagInputDialog::ids
    // end wxGlade

    TagInputDialog(wxWindow* parent, int id = wxID_ANY, const wxString& title = wxEmptyString, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    const wxString Title() const;
    const wxString Description() const;

    void SetTagTitle(const wxString& title);
    void SetTagDescription(const wxString& desc);

private:
    // begin wxGlade: TagInputDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: TagInputDialog::attributes
    wxStaticBox* sizer_2_staticbox;
    wxStaticText* label_1;
    wxTextCtrl* m_textTitle;
    wxStaticText* label_2;
    wxTextCtrl* m_textDescription;
    wxButton* button_1;
    wxPanel* panel_1;
    wxButton* button_2;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnTitleText(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // TAGINPUTDIALOG_H
