// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Dec 08 14:28:26 2011

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
#include <wx/datectrl.h>
// end wxGlade


#ifndef CLIENTDATAEXPORTDIALOG_H
#define CLIENTDATAEXPORTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

class CDBAccess;

class ClientDataExportDialog: public wxDialog {
private:
    static const wxString TITLE;
public:
    // begin wxGlade: ClientDataExportDialog::ids
    // end wxGlade

    ClientDataExportDialog(CDBAccess* dbaccess, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ClientDataExportDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ClientDataExportDialog::attributes
    wxStaticText* label_1;
    wxStaticLine* static_line_1;
    wxRadioButton* radioAll;
    wxRadioButton* radioDate;
    wxCheckBox* checkLess;
    wxDatePickerCtrl* dateLess;
    wxCheckBox* checkGreater;
    wxDatePickerCtrl* dateGreater;
    wxRadioButton* radioTag;
    wxStaticText* label_4;
    wxComboBox* listTag;
    wxStaticText* label_1_copy;
    wxStaticLine* static_line_1_copy;
    wxStaticText* label_5;
    wxTextCtrl* editOutput;
    wxButton* btnBrowse;
    wxStaticLine* static_line_2;
    wxButton* btnExport;
    wxPanel* panel_1;
    wxButton* btnClose;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnRadioAllClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioDateClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCheckLessClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCheckGreaterClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioTagClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnBrowseClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnCloseClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnExportClick(wxCommandEvent &event); // wxGlade: <event_handler>
private:
    int Export();
    int MakeSQL(wxString& sql);
    int OpenDB(const wxString& file, wxSQLite3Database& db);
    int TransDB(wxSQLite3Database& db, const wxString& sql);
    void CloseDB(wxSQLite3Database& db);
private:
    CDBAccess* _objDBAccess;
}; // wxGlade: end class


#endif // CLIENTDATAEXPORTDIALOG_H
