// -*- C++ -*- generated by wxGlade 0.6.5 (standalone edition) on Thu May 31 14:12:27 2012

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef DATACLEANUPDIALOG_H
#define DATACLEANUPDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

class CDBAccess;
class CDictObject;

class DataCleanupDialog: public wxDialog {
private:
		static const wxString	PLUGINS_TITLE;
public:
    // begin wxGlade: DataCleanupDialog::ids
    // end wxGlade

    DataCleanupDialog(CDBAccess* dbaccess, CDictObject* dict, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: DataCleanupDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: DataCleanupDialog::attributes
    wxStaticText* label_1;
    wxButton* btnBackup;
    wxStaticLine* static_line_1;
    wxGauge* barProcess;
    wxButton* btnCleanup;
	wxCheckBox* checkRemoveNotMatch;
    wxStaticLine* static_line_2;
    wxPanel* panel_1;
    wxButton* btnClose;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtnBackup(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnCleanup(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	int Cleanup();
	int DeleteData(int srcid);
	void EnableButtons(bool flag);
	int RemoveNotMatchData(int& found);
	bool IsNotMatchData(const wxString& html) const;
	int DeleteWord(int wordid);
private:
	CDBAccess* _objDBAccess;
	CDictObject* _objDict;
}; // wxGlade: end class


#endif // DATACLEANUPDIALOG_H
