// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jan 04 18:13:06 2011

#include <memory>

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
#include <wx/statline.h>
// end wxGlade


#ifndef TESTPLUGINSFRAME_H
#define TESTPLUGINSFRAME_H


// begin wxGlade: ::extracode
// end wxGlade


class CTestPluginObject;

class TestFrame: public wxFrame {
public:
    // begin wxGlade: TestFrame::ids
    // end wxGlade

    TestFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: TestFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

public:
    // begin wxGlade: TestFrame::attributes
    wxListCtrl* m_listPlugins;
    wxButton* button_1;
    wxPanel* panel_1;
    wxButton* button_2;
    wxStaticLine* static_line_1;
    wxPanel* panel_2;
    wxButton* button_3;
    wxPanel* panel_3;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnListDeselected(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnListSelected(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnDetail(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnRun(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
private:
    std::auto_ptr<CTestPluginObject> _objTestPlugins;
}; // wxGlade: end class



class MyApp: public wxApp {
public:
    bool OnInit();
};


DECLARE_APP(MyApp)

#endif // TESTPLUGINSFRAME_H
