// -*- C++ -*- generated by wxGlade 0.6.5 (standalone edition) on Mon May 21 17:16:58 2012

#include "SeparatorDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



SeparatorDialog::SeparatorDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: SeparatorDialog::SeparatorDialog
    label_6 = new wxStaticText(this, wxID_ANY, wxT("Separator"));
    static_line_7 = new wxStaticLine(this, wxID_ANY);
    m_rdSepCRLF = new wxRadioButton(this, 1010, wxT("by CRLF"), wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    m_rdSepComma = new wxRadioButton(this, 1011, wxT("by Comma"));
    m_rdSepSemi = new wxRadioButton(this, 1012, wxT("by Semicolon"));
    m_rdSepVertical = new wxRadioButton(this, 1015, wxT("by Vertical Line"));
    m_rdSepCustom = new wxRadioButton(this, 1013, wxT("by Custom"));
    m_editSepCustom = new wxTextCtrl(this, 1014, wxEmptyString);
    static_line_6 = new wxStaticLine(this, wxID_ANY);
    button_5 = new wxButton(this, wxID_OK, wxEmptyString);
    panel_1 = new wxPanel(this, wxID_ANY);
    button_6 = new wxButton(this, wxID_CANCEL, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(SeparatorDialog, wxDialog)
    // begin wxGlade: SeparatorDialog::event_table
    EVT_RADIOBUTTON(1010, SeparatorDialog::OnRadioSeparatorClick)
    EVT_RADIOBUTTON(1011, SeparatorDialog::OnRadioSeparatorClick)
    EVT_RADIOBUTTON(1012, SeparatorDialog::OnRadioSeparatorClick)
    EVT_RADIOBUTTON(1013, SeparatorDialog::OnRadioSeparatorClick)
	EVT_BUTTON(wxID_OK, SeparatorDialog::OnBtnOK)
    // end wxGlade
END_EVENT_TABLE();


void SeparatorDialog::OnRadioSeparatorClick(wxCommandEvent &event)
{
	m_editSepCustom->Enable(m_rdSepCustom->GetValue());	
}

void SeparatorDialog::OnBtnOK(wxCommandEvent &event)
{
	if(m_rdSepCRLF->GetValue())
	{
		m_strSeparator = wxT("\r\n");
	}
	else if(m_rdSepComma->GetValue())
	{
		m_strSeparator = wxT(",");
	}
	else if(m_rdSepSemi->GetValue())
	{
		m_strSeparator = wxT(";");
	}
	else if(m_rdSepVertical->GetValue())
	{
		m_strSeparator = wxT("|");
	}
	else if(m_rdSepCustom->GetValue())
	{
		m_strSeparator = m_editSepCustom->GetValue();
	}

	wxDialog::EndModal(wxID_OK);
//	wxDialog::Close();
}

// wxGlade: add SeparatorDialog event handlers


void SeparatorDialog::set_properties()
{
    // begin wxGlade: SeparatorDialog::set_properties
    SetTitle(wxT("Select Separator"));
    label_6->SetFont(wxFont(9, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    m_rdSepCRLF->SetValue(1);
    m_editSepCustom->Enable(false);
    // end wxGlade
}


void SeparatorDialog::do_layout()
{
    // begin wxGlade: SeparatorDialog::do_layout
    wxBoxSizer* sizer_27 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_29 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_16 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_19 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_15 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_14 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_13 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_28 = new wxBoxSizer(wxHORIZONTAL);
    sizer_28->Add(label_6, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_28->Add(static_line_7, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_6->Add(sizer_28, 1, wxALL|wxEXPAND, 4);
    sizer_13->Add(20, 20, 0, 0, 0);
    sizer_13->Add(m_rdSepCRLF, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_13, 0, wxRIGHT|wxEXPAND, 4);
    sizer_14->Add(20, 20, 0, 0, 0);
    sizer_14->Add(m_rdSepComma, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_14, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_15->Add(20, 20, 0, 0, 0);
    sizer_15->Add(m_rdSepSemi, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_15, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_19->Add(20, 20, 0, 0, 0);
    sizer_19->Add(m_rdSepVertical, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_19, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_16->Add(20, 20, 0, 0, 0);
    sizer_16->Add(m_rdSepCustom, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_16->Add(m_editSepCustom, 3, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_16, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_27->Add(sizer_6, 0, wxALL|wxEXPAND, 4);
    sizer_27->Add(static_line_6, 0, wxALL|wxEXPAND|wxALIGN_CENTER_VERTICAL, 4);
    sizer_29->Add(button_5, 0, 0, 0);
    sizer_29->Add(panel_1, 1, wxEXPAND, 0);
    sizer_29->Add(button_6, 0, 0, 0);
    sizer_27->Add(sizer_29, 1, wxALL|wxEXPAND, 8);
    SetSizer(sizer_27);
    sizer_27->Fit(this);
    Layout();
    // end wxGlade
}

