// -*- C++ -*- generated by wxGlade 0.6.5 (standalone edition) on Mon May 21 15:48:48 2012

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef WORDEXPORTV2DIALOG_H
#define WORDEXPORTV2DIALOG_H

#include "HtmlOptimumConfigDialog.h"

// begin wxGlade: ::extracode
// end wxGlade

class CDBAccess;

class WordExportV2Dialog: public wxDialog {
public:
    // begin wxGlade: WordExportV2Dialog::ids
    // end wxGlade

    WordExportV2Dialog(CDBAccess* dbaccess, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: WordExportV2Dialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WordExportV2Dialog::attributes
    wxStaticText* label_1;
    wxStaticLine* static_line_1;
    wxRadioButton* radioWordAll;
    wxCheckBox* checkWordPrefix;
    wxTextCtrl* textWordPrefix;
    wxCheckBox* checkWordSuffix;
    wxTextCtrl* textWordSuffix;
    wxStaticText* label_3;
    wxStaticLine* static_line_2;
    wxRadioButton* radioTagAll;
    wxRadioButton* radioTagSpecific;
    wxComboBox* comboTagSpecific;
    wxStaticText* label_4;
    wxStaticLine* static_line_3;
    wxRadioButton* radioDictAll;
    wxRadioButton* radioDictSpecific;
    wxComboBox* comboDictSpecific;
    wxStaticText* label_5;
    wxStaticLine* static_line_4;
    wxRadioButton* radioOutputHtml;
    wxButton* btnOutputOptimum;
    wxRadioButton* radioOutputLAC;
    wxRadioButton* radioOutputWord;
    wxButton* btnOutputWord;
    wxStaticText* label_6;
    wxStaticLine* static_line_5;
    wxTextCtrl* textExport;
    wxButton* btnExportBrowse;
    wxStaticLine* static_line_6;
    wxButton* btnExport;
    wxPanel* panel_1;
    wxButton* btnClose;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnCheckWordClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioTagClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioDictClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioOutputClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnOptimizer(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnSeparator(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnTextExport(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnExport(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	int InitTag();
	int InitDict();
private:
	CDBAccess* _objDBAccess;
	CDocumentOutputObject::TKeyMap _mapOptimumKey;
	wxString _strSeparator;
}; // wxGlade: end class


#endif // WORDEXPORTV2DIALOG_H
