// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jan 11 23:11:16 2011

#include "WordExportDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



WordExportDialog::WordExportDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME)
{
    // begin wxGlade: WordExportDialog::WordExportDialog
    panel_1 = new wxPanel(this, wxID_ANY);
    button_1 = new wxButton(this, wxID_CLOSE, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(WordExportDialog, wxDialog)
    // begin wxGlade: WordExportDialog::event_table
    EVT_BUTTON(wxID_CLOSE, WordExportDialog::OnBtnClose)
    // end wxGlade
END_EVENT_TABLE();


void WordExportDialog::OnBtnClose(wxCommandEvent &event)
{
    Close();
}


// wxGlade: add WordExportDialog event handlers


void WordExportDialog::set_properties()
{
    // begin wxGlade: WordExportDialog::set_properties
    SetTitle(wxT("Word Export - LingosHook Plugins"));
    // end wxGlade
}


void WordExportDialog::do_layout()
{
    // begin wxGlade: WordExportDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(panel_1, 1, wxEXPAND, 0);
    sizer_2->Add(button_1, 0, 0, 0);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

