

// -*- C++ -*- generated by wxGlade 0.6.5 (standalone edition) on Mon May 21 15:48:48 2012











#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade






#ifndef WORDEXPORTV2DIALOG_H
#define WORDEXPORTV2DIALOG_H

#include "DBAccess.h"
#include "HtmlOptimumConfigDialog.h"
#include "ExtendStyleDialog.h"



// begin wxGlade: ::extracode
// end wxGlade


class WordExportV2Dialog: public wxDialog {
private:
	static const wxString	PLUGINS_TITLE;
	static const wxString	EXPORT_FILENAME;
	static const wxString	INDEX_FILENAME;
	static const wxString	DATA_FILENAME;

	enum ExportType { ET_UNKNOWN = -1, ET_HTML_INDEX_S = 0, ET_HTML_INDEX_M, ET_HTML, ET_LAC, ET_TEXT };
public:
    // begin wxGlade: WordExportV2Dialog::ids
    // end wxGlade

    WordExportV2Dialog(CDBAccess* dbaccess, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: WordExportV2Dialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WordExportV2Dialog::attributes
    wxStaticText* label_1;
    wxStaticLine* static_line_1;
    wxRadioButton* radioWordAll;
    wxPanel* panel_2;
    wxCheckBox* checkOrder;
    wxCheckBox* checkWordPrefix;
    wxTextCtrl* textWordPrefix;
    wxCheckBox* checkWordSuffix;
    wxTextCtrl* textWordSuffix;
    wxStaticText* label_3;
    wxStaticLine* static_line_2;
    wxRadioButton* radioTagAll;
    wxRadioButton* radioTagSpecific;
    wxComboBox* comboTagSpecific;
    wxStaticText* label_4;
    wxStaticLine* static_line_3;
    wxRadioButton* radioDictAll;
    wxRadioButton* radioDictSpecific;
    wxComboBox* comboDictSpecific;
    wxStaticText* label_5;
    wxStaticLine* static_line_4;
    wxRadioButton* radioOutputHtmlSingle;
    wxButton* btnOutputOptimumSingle;
    wxRadioButton* radioOutputHtmlMulti;
    wxButton* btnOutputOptimumMulti;
    wxRadioButton* radioOutputHtml;
    wxButton* btnOutputOptimum;
    wxRadioButton* radioOutputLAC;
    wxRadioButton* radioOutputWord;
    wxButton* btnOutputWord;
    wxStaticText* label_6;
    wxStaticLine* static_line_5;
    wxTextCtrl* textExport;
    wxButton* btnExportBrowse;
    wxStaticLine* static_line_6;
    wxButton* btnExport;
    wxPanel* panel_1;
    wxButton* btnStyle;
    wxPanel* panel_3;
    wxButton* btnClose;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnCheckWordClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioTagClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioDictClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioOutputClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnOptimizer(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnSeparator(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnTextExport(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnExport(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
	virtual void OnBtnStyle(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	int InitTag();
	int InitDict();
	void InitOptimumKey();

	int Export();

	int ExportHtmlWithIndexSingle(CDBAccess::TResult& res);
	int ExportHtmlWithIndexMulti(CDBAccess::TResult& res);
	int ExportHtml(CDBAccess::TResult& res);
	int ExportLAC(CDBAccess::TResult& res);
	int ExportText(CDBAccess::TResult& res);

	const wxString MakeExportPath() const;
	const wxString GetExportFilename() const;
	const wxString GetIndexFilename() const;
	const wxString GetDataFilename() const;
	const wxString MakeExportSql();
	int CheckHtmlOptimumKey();
	int FilterHtml(const wxString& input, wxString& output, const CDocumentOutputObject::TKeyMap& mapKey) const;
	void WordExportV2Dialog::RemoveTable(CDBAccess::TDatabase& db, const wxString& name) const;
private:
	CDBAccess* _objDBAccess;
	CDocumentOutputObject::TKeyMap _mapOptimumKey;
	ExportType _eExportType;
	wxString _strSeparator;
	wxString _strFilterDict;

	ExtendStyleDialog::StyleData _dataStyle;
//	wxString _strExportPath;
}; // wxGlade: end class


#endif // WORDEXPORTV2DIALOG_H
