// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jan 11 23:11:16 2011

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef WORDEXPORTDIALOG_H
#define WORDEXPORTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade


class WordExportDialog: public wxDialog {
public:
    // begin wxGlade: WordExportDialog::ids
    // end wxGlade

    WordExportDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: WordExportDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WordExportDialog::attributes
    wxPanel* panel_1;
    wxButton* button_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // WORDEXPORTDIALOG_H
