// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jan 14 18:02:29 2011

#include "WordExportDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



WordExportDialog::WordExportDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME)
{
    // begin wxGlade: WordExportDialog::WordExportDialog
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Range"));
    m_rdRangeAll = new wxRadioButton(this, 1000, wxT("All Words"), wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    m_rdRangeAlphabet = new wxRadioButton(this, 1001, wxT("Alphabet"));
    const wxString m_listRangeLow_choices[] = {
        wxT("A"),
        wxT("B"),
        wxT("C")
    };
    m_listRangeLow = new wxComboBox(this, 1004, wxT(""), wxDefaultPosition, wxDefaultSize, 3, m_listRangeLow_choices, wxCB_DROPDOWN|wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    label_5 = new wxStaticText(this, wxID_ANY, wxT("~"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE);
    const wxString *m_listRangeHigh_choices = NULL;
    m_listRangeHigh = new wxComboBox(this, 1005, wxT(""), wxDefaultPosition, wxDefaultSize, 0, m_listRangeHigh_choices, wxCB_DROPDOWN|wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    m_rdRangePrefix = new wxRadioButton(this, 1002, wxT("Prefix"));
    m_editRangePrefix = new wxTextCtrl(this, 1006, wxEmptyString);
    m_rdRangeSuffix = new wxRadioButton(this, 1003, wxT("Suffix"));
    m_editRangeSuffix = new wxTextCtrl(this, 1007, wxEmptyString);
    static_line_1 = new wxStaticLine(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_VERTICAL);
    label_2 = new wxStaticText(this, wxID_ANY, wxT("Separator"));
    m_rdSepCRLF = new wxRadioButton(this, 1010, wxT("by CRLF"), wxDefaultPosition, wxDefaultSize, wxRB_GROUP);
    m_rdSepComma = new wxRadioButton(this, 1011, wxT("by Comma"));
    m_rdSepSemi = new wxRadioButton(this, 1012, wxT("by Semicolon"));
    m_rdSepCustom = new wxRadioButton(this, 1013, wxT("by Custom"));
    m_editSepCustom = new wxTextCtrl(this, 1014, wxEmptyString);
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    label_3 = new wxStaticText(this, wxID_ANY, wxT("Options"));
    m_cbOptionSymbol = new wxCheckBox(this, 1020, wxT("with Phonetic Symbol"));
    m_cbOptionNumber = new wxCheckBox(this, 1021, wxT("Number of Words per File"));
    m_editOptionNum = new wxTextCtrl(this, 1022, wxEmptyString);
    static_line_3 = new wxStaticLine(this, wxID_ANY);
    label_4 = new wxStaticText(this, wxID_ANY, wxT("Export"));
    m_editExportFile = new wxStaticText(this, wxID_ANY, wxT("Output File"));
    text_ctrl_1 = new wxTextCtrl(this, 1030, wxEmptyString);
    m_btnExportBrowse = new wxButton(this, 1031, wxT("Browse.."));
    panel_3 = new wxPanel(this, wxID_ANY);
    m_btnExport = new wxButton(this, 1032, wxT("Export !"));
    panel_4 = new wxPanel(this, wxID_ANY);
    static_line_4 = new wxStaticLine(this, wxID_ANY);
    panel_5 = new wxPanel(this, wxID_ANY);
    m_btnClose = new wxButton(this, wxID_CLOSE, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


void WordExportDialog::set_properties()
{
    // begin wxGlade: WordExportDialog::set_properties
    SetTitle(wxT("Word Export - LingosHook Plugins"));
    SetSize(wxSize(472, 396));
    label_1->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    m_rdRangeAll->SetValue(1);
    m_listRangeLow->Enable(false);
    m_listRangeLow->SetSelection(-1);
    m_listRangeHigh->Enable(false);
    m_editRangePrefix->Enable(false);
    m_editRangeSuffix->Enable(false);
    label_2->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    m_rdSepCRLF->SetValue(1);
    m_editSepCustom->Enable(false);
    label_3->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    m_editOptionNum->Enable(false);
    label_4->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    m_btnExport->Enable(false);
    // end wxGlade
}


void WordExportDialog::do_layout()
{
    // begin wxGlade: WordExportDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_21 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_20 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_22 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_18 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_17 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_16 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_15 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_14 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_13 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_12 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_11 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    sizer_5->Add(label_1, 0, wxALL, 4);
    sizer_9->Add(20, 20, 0, 0, 0);
    sizer_9->Add(m_rdRangeAll, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_5->Add(sizer_9, 0, wxRIGHT|wxEXPAND, 4);
    sizer_10->Add(20, 20, 0, 0, 0);
    sizer_10->Add(m_rdRangeAlphabet, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_10->Add(m_listRangeLow, 1, wxALIGN_CENTER_VERTICAL, 0);
    sizer_10->Add(label_5, 1, wxALIGN_CENTER_VERTICAL, 0);
    sizer_10->Add(m_listRangeHigh, 1, wxALIGN_CENTER_VERTICAL, 0);
    sizer_5->Add(sizer_10, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_11->Add(20, 20, 0, 0, 0);
    sizer_11->Add(m_rdRangePrefix, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_11->Add(m_editRangePrefix, 3, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_5->Add(sizer_11, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_12->Add(20, 20, 0, 0, 0);
    sizer_12->Add(m_rdRangeSuffix, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_12->Add(m_editRangeSuffix, 3, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_5->Add(sizer_12, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_4->Add(sizer_5, 1, wxEXPAND, 0);
    sizer_4->Add(static_line_1, 0, wxLEFT|wxTOP|wxEXPAND, 16);
    sizer_6->Add(label_2, 0, wxALL, 4);
    sizer_13->Add(20, 20, 0, 0, 0);
    sizer_13->Add(m_rdSepCRLF, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_13, 0, wxRIGHT|wxEXPAND, 4);
    sizer_14->Add(20, 20, 0, 0, 0);
    sizer_14->Add(m_rdSepComma, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_14, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_15->Add(20, 20, 0, 0, 0);
    sizer_15->Add(m_rdSepSemi, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_15, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_16->Add(20, 20, 0, 0, 0);
    sizer_16->Add(m_rdSepCustom, 2, wxALIGN_CENTER_VERTICAL, 0);
    sizer_16->Add(m_editSepCustom, 3, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    sizer_6->Add(sizer_16, 0, wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_4->Add(sizer_6, 1, wxEXPAND, 0);
    sizer_3->Add(sizer_4, 0, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_3->Add(static_line_2, 0, wxALL|wxEXPAND, 8);
    sizer_7->Add(label_3, 0, wxLEFT|wxRIGHT, 4);
    sizer_17->Add(20, 20, 0, 0, 0);
    sizer_17->Add(m_cbOptionSymbol, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 4);
    sizer_7->Add(sizer_17, 0, wxTOP|wxEXPAND, 4);
    sizer_18->Add(20, 20, 0, 0, 0);
    sizer_18->Add(m_cbOptionNumber, 0, wxBOTTOM|wxALIGN_CENTER_VERTICAL, 4);
    sizer_18->Add(m_editOptionNum, 0, wxLEFT|wxALIGN_CENTER_VERTICAL, 4);
    sizer_7->Add(sizer_18, 0, wxTOP|wxEXPAND, 4);
    sizer_3->Add(sizer_7, 0, wxLEFT|wxRIGHT|wxEXPAND, 4);
    sizer_3->Add(static_line_3, 0, wxALL|wxEXPAND, 8);
    sizer_8->Add(label_4, 0, wxALL, 4);
    sizer_22->Add(20, 20, 0, 0, 0);
    sizer_22->Add(m_editExportFile, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_22->Add(text_ctrl_1, 1, wxLEFT|wxALIGN_CENTER_VERTICAL, 4);
    sizer_22->Add(m_btnExportBrowse, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_8->Add(sizer_22, 1, wxEXPAND, 4);
    sizer_20->Add(panel_3, 2, wxEXPAND, 0);
    sizer_20->Add(m_btnExport, 3, 0, 0);
    sizer_20->Add(panel_4, 2, wxEXPAND, 0);
    sizer_8->Add(sizer_20, 0, wxTOP|wxEXPAND, 8);
    sizer_3->Add(sizer_8, 0, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_1->Add(sizer_3, 1, wxEXPAND, 0);
    sizer_1->Add(static_line_4, 0, wxALL|wxEXPAND, 4);
    sizer_21->Add(panel_5, 1, wxEXPAND, 0);
    sizer_21->Add(m_btnClose, 0, 0, 0);
    sizer_1->Add(sizer_21, 0, wxALL|wxEXPAND, 4);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

