// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Jan 26 17:25:45 2011

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef WORDEXPORTDIALOG_H
#define WORDEXPORTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

class CDBAccess;

class WordExportDialog: public wxDialog {
public:
    // begin wxGlade: WordExportDialog::ids
    // end wxGlade

    WordExportDialog(CDBAccess* dbaccess, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: WordExportDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WordExportDialog::attributes
    wxStaticText* label_1;
    wxRadioButton* m_rdRangeAll;
    wxRadioButton* m_rdRangeAlphabet;
    wxComboBox* m_listRangeLow;
    wxStaticText* label_5;
    wxComboBox* m_listRangeHigh;
    wxRadioButton* m_rdRangePrefix;
    wxTextCtrl* m_editRangePrefix;
    wxRadioButton* m_rdRangeSuffix;
    wxTextCtrl* m_editRangeSuffix;
    wxRadioButton* m_rdRangeTag;
    wxTextCtrl* m_editRangeTag;
    wxStaticLine* static_line_1;
    wxStaticText* label_2;
    wxRadioButton* m_rdSepCRLF;
    wxRadioButton* m_rdSepComma;
    wxRadioButton* m_rdSepSemi;
    wxRadioButton* m_rdSepVertical;
    wxRadioButton* m_rdSepCustom;
    wxTextCtrl* m_editSepCustom;
    wxStaticLine* static_line_2;
    wxStaticText* label_3;
    wxCheckBox* m_cbOptionSymbol;
    wxCheckBox* m_cbOptionNumber;
    wxTextCtrl* m_editOptionNum;
    wxStaticLine* static_line_3;
    wxStaticText* label_4;
    wxStaticText* m_editExportFile;
    wxTextCtrl* m_editOutput;
    wxButton* m_btnExportBrowse;
    wxPanel* panel_3;
    wxButton* m_btnExport;
    wxPanel* panel_4;
    wxStaticLine* static_line_4;
    wxPanel* panel_5;
    wxButton* m_btnClose;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnRadioRangeClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioSeparatorClick(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnCheckOptionWord(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnEditOutputText(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnExport(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnClose(wxCommandEvent &event); // wxGlade: <event_handler>
private:
    int MakeSQL(wxString& sql) const;
    int MakeSeparator(wxString& sep) const;
    int ExportFile(const wxString& file, const wxString& suffix, const wxString& sql, const wxString& sep, long num);

    int Export();
private:
    CDBAccess* _objDBAccess;
}; // wxGlade: end class


#endif // WORDEXPORTDIALOG_H
