// -*- C++ -*-
//
// generated by wxGlade 0.6.8 (standalone edition) on Thu Oct 24 21:31:58 2013
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef EXTENDSTYLEDIALOG_H
#define EXTENDSTYLEDIALOG_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class ExtendStyleDialog: public wxDialog {

public:
	class StyleData
	{
	public:
		StyleData()
			: strFontSize(wxT("11pt"))
			, strTextColor(wxEmptyString)
			, strBackgroundColor(wxEmptyString)
			, iFontStyle(1)
			, strContentIndentation(wxEmptyString)
		{
		}

	public:
		wxString strFontSize;
		wxString strTextColor;
		wxString strBackgroundColor;
		int iFontStyle;// 1: bold; 2: italic; 4: bold & italic
		wxString strContentIndentation;
	};

public:
    // begin wxGlade: ExtendStyleDialog::ids
    // end wxGlade

    ExtendStyleDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ExtendStyleDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ExtendStyleDialog::attributes
    wxStaticText* label_1;
    wxStaticLine* static_line_4;
    wxStaticText* label_17;
    wxComboBox* comboxFontSize;
    wxStaticText* label_18;
    wxComboBox* comboxTextColor;
    wxStaticText* label_19;
    wxComboBox* comboxBgColor;
    wxStaticText* label_20;
    wxChoice* listFontStyle;
    wxStaticText* label_9;
    wxStaticLine* static_line_3;
    wxStaticText* label_10;
    wxComboBox* comboxIndentation;
    wxStaticLine* static_line_5;
    wxButton* button_1;
    wxPanel* panel_1;
    wxButton* button_2;
    // end wxGlade
    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtenOK(wxCommandEvent &event); // wxGlade: <event_handler>	
private:
	StyleData _dataStyle;

	void MakeStyleData(StyleData& data);
public:
	const StyleData& GetStyleData() const;
}; // wxGlade: end class


#endif // EXTENDSTYLEDIALOG_H
