// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Jun 28 10:09:51 2010

#include <wx/wx.h>
//#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/checklst.h>
#include <wx/statline.h>
// end wxGlade


#ifndef DICTCHOICEDIALOG_H
#define DICTCHOICEDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

#include "LHControls.h"

class CDictObject;

class CHtmlDictLoadChoiceDialog: public wxDialog {
public:
    // begin wxGlade: CHtmlDictLoadChoiceDialog::ids
    // end wxGlade

    CHtmlDictLoadChoiceDialog(CDictObject* parser, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    CLHCheckBoxList& ListCtrl() { return *m_listDict; }
    const CLHCheckBoxList& ListCtrl() const { return *m_listDict; }
    void SetUseDictRadio(int usedict);
    int GetUseDictRadio(int& usedict) const;
private:
    // begin wxGlade: CHtmlDictLoadChoiceDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CHtmlDictLoadChoiceDialog::attributes
    wxStaticBox* sizer_1_staticbox;

    wxRadioButton* m_radioDictChoose;
    //CLHCheckBoxList* m_listDict;
    CLHCheckBoxList* m_listDict;
    wxPanel* panel_1;
    wxButton* m_btnDictTop;
    wxButton* m_btnDictUp;
    wxButton* m_btnDictDown;
    wxButton* m_btnDictBottom;
    wxStaticLine* static_line_4;

    wxRadioButton* m_radioDictAuto;
    wxRadioButton* m_radioDictNo;
    wxStaticLine* static_line_1;
    wxButton* m_btnDictCancel;
    wxPanel* panel_2;
    wxButton* m_btnDictOK;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtnDictTop(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnDictUp(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnDictDown(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnDictBottom(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioDict(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioNoDict(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnRadioDictAuto(wxCommandEvent &event); // wxGlade: <event_handler>
private:
    CDictObject* _objParser;

}; // wxGlade: end class



#endif // DICTCHOICEDIALOG_H
