// -*- C++ -*- generated by wxGlade 0.6.5 (standalone edition) on Thu May 10 17:35:25 2012

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef HTMLOPTIMUMCONFIGDIALOG_H
#define HTMLOPTIMUMCONFIGDIALOG_H

#include "ConfigData.h"

// begin wxGlade: ::extracode
// end wxGlade


class HtmlOptimumConfigDialog: public wxDialog {
private:
	const static wxString STR_TAG_DEFAULT;
	const static wxString STR_TAG_ALL;
	const static wxString STR_TAG_LINK;
	const static wxString STR_TAG_IMG;
	const static wxString STR_TAG_OBJECT;
	const static wxString STR_TAG_EMBED;
	const static wxString STR_TAG_PARAM;

	const static wxString STR_ATTR_DEFAULT;
	const static wxString STR_ATTR_ALL;
	const static wxString STR_ATTR_CLASS;
	const static wxString STR_ATTR_ONCLICK;
	const static wxString STR_ATTR_ONMOUSEOUT;
	const static wxString STR_ATTR_ONMOUSEOVER;
	const static wxString STR_ATTR_ONMOUSEUP;
	const static wxString STR_ATTR_ONMOUSEDOWN;
	const static wxString STR_ATTR_ONSELECTSTART;

	const static wxString STR_VALUE_DEFAULT;
	const static wxString STR_VALUE_ALL;

public:
    // begin wxGlade: HtmlOptimumConfigDialog::ids
    // end wxGlade

    HtmlOptimumConfigDialog(CConfigData* conf, wxWindow* parent, int id, const wxString& title = wxEmptyString, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: HtmlOptimumConfigDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HtmlOptimumConfigDialog::attributes
    wxStaticText* label_1;
    wxStaticLine* static_line_2;
    wxComboBox* comboTag;
    wxButton* button_4;
    wxListBox* listTag;
    wxButton* button_5;
    wxButton* button_6;
    wxPanel* panel_2;
    wxStaticText* label_1_copy;
    wxStaticLine* static_line_2_copy;
    wxComboBox* comboAttrib;
    wxButton* button_4_copy;
    wxListBox* listAttrib;
    wxButton* button_5_copy;
    wxButton* button_6_copy;
    wxPanel* panel_2_copy;
    wxStaticText* label_1_copy_1;
    wxStaticLine* static_line_2_copy_1;
    wxComboBox* comboValue;
    wxButton* button_4_copy_1;
    wxListBox* listValue;
    wxButton* button_5_copy_1;
    wxButton* button_6_copy_1;
    wxPanel* panel_2_copy_1;
    wxStaticLine* static_line_1;
    wxButton* button_1;
    wxPanel* panel_1;
    wxButton* button_2;
    wxButton* button_3;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnBtnTagAdd(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnTagRemove(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnTagRemoveAll(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnAttrAdd(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnAttrRemove(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnAttrRemoveAll(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnValAdd(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnValRemove(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnValRemoveAll(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnDefault(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnOK(wxCommandEvent &event); // wxGlade: <event_handler>
private:
	int InitConfig();
	int UpdateConfig();
private:
    CConfigData* _config;
}; // wxGlade: end class


#endif // HTMLOPTIMUMCONFIGDIALOG_H
