// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Apr 06 18:27:07 2010

#include "ExceptionRaisedDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



CExceptionRaisedDialog::CExceptionRaisedDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: CExceptionRaisedDialog::CExceptionRaisedDialog
    label_2 = new wxStaticText(this, wxID_ANY, wxT("A...ah..EXCEPTION raised. Please copy the blew content and sent it to me."));
    label_3 = new wxStaticText(this, wxID_ANY, wxT("Thank you to help me to improve LingosHook!"), wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT|wxST_NO_AUTORESIZE);
    static_line_1 = new wxStaticLine(this, wxID_ANY);
    m_textInfo = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_READONLY);
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    m_btnCopy = new wxButton(this, 15100, wxT("Copy it to Clipboard"));
    m_btnSend = new wxButton(this, 15101, wxT("Send it by Email"));
    m_btnPost = new wxButton(this, 15102, wxT("Post it to Blog"));
    panel_1 = new wxPanel(this, wxID_ANY);
    m_btnOK = new wxButton(this, wxID_CLOSE, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(CExceptionRaisedDialog, wxDialog)
    // begin wxGlade: CExceptionRaisedDialog::event_table
    EVT_BUTTON(15100, CExceptionRaisedDialog::OnBtnCopy)
    EVT_BUTTON(15101, CExceptionRaisedDialog::OnBtnSend)
    EVT_BUTTON(15102, CExceptionRaisedDialog::OnBtnPost)
    EVT_BUTTON(wxID_CLOSE, CExceptionRaisedDialog::OnBtnOK)
    // end wxGlade
END_EVENT_TABLE();


void CExceptionRaisedDialog::OnBtnCopy(wxCommandEvent &event)
{
    m_textInfo->SelectAll();
    m_textInfo->Copy();

//    event.Skip();
//    wxLogDebug(wxT("Event handler (CExceptionRaisedDialog::OnBtnCopy) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void CExceptionRaisedDialog::OnBtnSend(wxCommandEvent &event)
{
    wxString cmd = _("mailto:codejie@gmail.com");
    ::wxLaunchDefaultBrowser(cmd);
//    event.Skip();
//    wxLogDebug(wxT("Event handler (CExceptionRaisedDialog::OnBtnSend) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void CExceptionRaisedDialog::OnBtnPost(wxCommandEvent &event)
{
    wxString cmd = _("http://www.cppblog.com/codejie");
    ::wxLaunchDefaultBrowser(cmd);
}

void CExceptionRaisedDialog::OnBtnOK(wxCommandEvent &event)
{
    Close();
    //event.Skip();
    //wxLogDebug(wxT("Event handler (CExceptionRaisedDialog::OnBtnPost) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}

// wxGlade: add CExceptionRaisedDialog event handlers


void CExceptionRaisedDialog::set_properties()
{
    // begin wxGlade: CExceptionRaisedDialog::set_properties
    SetTitle(wxT("LingosHook catches a Exception !"));
    m_textInfo->SetMinSize(wxSize(489, 295));
    // end wxGlade
}


void CExceptionRaisedDialog::do_layout()
{
    // begin wxGlade: CExceptionRaisedDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(label_2, 0, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_1->Add(label_3, 0, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_1->Add(static_line_1, 0, wxALL|wxEXPAND, 4);
    sizer_1->Add(m_textInfo, 1, wxEXPAND, 0);
    sizer_1->Add(static_line_2, 0, wxALL|wxEXPAND, 4);
    sizer_3->Add(m_btnCopy, 0, wxLEFT|wxRIGHT, 4);
    sizer_3->Add(m_btnSend, 0, wxLEFT|wxRIGHT, 4);
    sizer_3->Add(m_btnPost, 0, wxLEFT|wxRIGHT, 4);
    sizer_3->Add(panel_1, 1, wxEXPAND, 0);
    sizer_3->Add(m_btnOK, 0, 0, 0);
    sizer_1->Add(sizer_3, 0, wxALL|wxEXPAND, 4);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

void CExceptionRaisedDialog::SetInfo(const wxString &info)
{
    m_textInfo->SetValue(info);
}

