// -*- C++ -*- generated by wxGlade 0.6.3 on Fri Jan 14 18:02:29 2011

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef WORDEXPORTDIALOG_H
#define WORDEXPORTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade


class WordExportDialog: public wxDialog {
public:
    // begin wxGlade: WordExportDialog::ids
    // end wxGlade

    WordExportDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: WordExportDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: WordExportDialog::attributes
    wxStaticText* label_1;
    wxRadioButton* m_rdRangeAll;
    wxRadioButton* m_rdRangeAlphabet;
    wxComboBox* m_listRangeLow;
    wxStaticText* label_5;
    wxComboBox* m_listRangeHigh;
    wxRadioButton* m_rdRangePrefix;
    wxTextCtrl* m_editRangePrefix;
    wxRadioButton* m_rdRangeSuffix;
    wxTextCtrl* m_editRangeSuffix;
    wxStaticLine* static_line_1;
    wxStaticText* label_2;
    wxRadioButton* m_rdSepCRLF;
    wxRadioButton* m_rdSepComma;
    wxRadioButton* m_rdSepSemi;
    wxRadioButton* m_rdSepCustom;
    wxTextCtrl* m_editSepCustom;
    wxStaticLine* static_line_2;
    wxStaticText* label_3;
    wxCheckBox* m_cbOptionSymbol;
    wxCheckBox* m_cbOptionNumber;
    wxTextCtrl* m_editOptionNum;
    wxStaticLine* static_line_3;
    wxStaticText* label_4;
    wxStaticText* m_editExportFile;
    wxTextCtrl* text_ctrl_1;
    wxButton* m_btnExportBrowse;
    wxPanel* panel_3;
    wxButton* m_btnExport;
    wxPanel* panel_4;
    wxStaticLine* static_line_4;
    wxPanel* panel_5;
    wxButton* m_btnClose;
    // end wxGlade
}; // wxGlade: end class


#endif // WORDEXPORTDIALOG_H
