// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Aug 09 11:06:41 2010

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/statline.h>
// end wxGlade


#ifndef LHANALYSISFILTERDIALOG_H
#define LHANALYSISFILTERDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

class CConfigData;

class CAnalysisFilterDialog: public wxDialog {
public:
    // begin wxGlade: CAnalysisFilterDialog::ids
    // end wxGlade

    CAnalysisFilterDialog(const CConfigData* conf, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    const wxCheckBox* CheckBoxCase() const { return m_cbCase; }
    const wxCheckBox* CheckBoxOneWordEachDict() const { return m_cbOneWordEachDict; }
    const wxCheckBox* CheckBoxOneWordAllDict() const { return m_cbOneWordAllDict; }
private:
    // begin wxGlade: CAnalysisFilterDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CAnalysisFilterDialog::attributes
    wxStaticBox* sizer_1_staticbox;
    wxCheckBox* m_cbCase;
    wxCheckBox* m_cbOneWordEachDict;
    wxCheckBox* m_cbOneWordAllDict;
    wxStaticLine* static_line_1;
    wxButton* button_1;
    wxPanel* panel_1;
    wxButton* button_2;
private:
    const CConfigData* _config;
    // end wxGlade
}; // wxGlade: end class


#endif // LHANALYSISFILTERDIALOG_H
