// -*- C++ -*- generated by wxGlade 0.6.3 on Tue Jul 27 17:10:24 2010

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
#include <wx/statline.h>
// end wxGlade


#ifndef LHDICTDIALOG_H
#define LHDICTDIALOG_H


// begin wxGlade: ::extracode
// end wxGlade

#include "LHControls.h"

class CDictObject;

class CHtmlDictStoreChoiceDialog: public wxDialog {
public:
    // begin wxGlade: CHtmlDictStoreChoiceDialog::ids
    // end wxGlade

    CHtmlDictStoreChoiceDialog(CDictObject* parser, wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

    CLHCheckBoxList& ListCtrl() { return *m_listDict; }
    const CLHCheckBoxList& ListCtrl() const { return *m_listDict; }
private:
    // begin wxGlade: CHtmlDictStoreChoiceDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: CHtmlDictStoreChoiceDialog::attributes
    wxStaticBox* sizer_1_staticbox;
    CLHCheckBoxList* m_listDict;
    wxButton* m_btnReset;
    wxStaticText* label_1;
    wxStaticLine* static_line_1;
    wxButton* button_1;
    wxPanel* panel_1;
    wxButton* button_2;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void OnDictListRightClick(wxListEvent &event); // wxGlade: <event_handler>
    virtual void OnBtnReset(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void OnMenuItemDefType(wxCommandEvent& event);
private:
    CDictObject* _objParser;
}; // wxGlade: end class




#endif // LHDICTDIALOG_H
