// -*- C++ -*- generated by wxGlade 0.6.3 on Mon Mar 22 15:39:22 2010

#include "TagInputDialog.h"

// begin wxGlade: ::extracode
// end wxGlade



TagInputDialog::TagInputDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: TagInputDialog::TagInputDialog
    sizer_2_staticbox = new wxStaticBox(this, -1, _("Title && Description"));
    label_1 = new wxStaticText(this, wxID_ANY, _("Title:"), wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    m_textTitle = new wxTextCtrl(this, 15000, wxEmptyString);
    label_2 = new wxStaticText(this, wxID_ANY, _("Description:"), wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    m_textDescription = new wxTextCtrl(this, 15001, wxEmptyString);
    button_1 = new wxButton(this, wxID_CANCEL, _("Cancel"));
    panel_1 = new wxPanel(this, wxID_ANY);
    button_2 = new wxButton(this, wxID_OK, _("OK"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(TagInputDialog, wxDialog)
    // begin wxGlade: TagInputDialog::event_table
    EVT_TEXT(15000, TagInputDialog::OnTitleText)
    // end wxGlade
END_EVENT_TABLE();


void TagInputDialog::OnTitleText(wxCommandEvent &event)
{
    button_2->Enable((m_textTitle->GetValue().size() > 0));
    //event.Skip();
    //wxLogDebug(wxT("Event handler (TagInputDialog::OnTitleText) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add TagInputDialog event handlers


void TagInputDialog::set_properties()
{
    // begin wxGlade: TagInputDialog::set_properties
    SetTitle(_("Input Tag Info.."));
    button_2->Enable(false);
    // end wxGlade
}


void TagInputDialog::do_layout()
{
    // begin wxGlade: TagInputDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* sizer_2 = new wxStaticBoxSizer(sizer_2_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    sizer_3->Add(label_1, 1, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 4);
    sizer_3->Add(m_textTitle, 4, wxLEFT|wxRIGHT|wxEXPAND, 4);
    sizer_2->Add(sizer_3, 0, wxTOP|wxBOTTOM|wxEXPAND, 4);
    sizer_4->Add(label_2, 1, wxLEFT|wxRIGHT|wxALIGN_CENTER_VERTICAL, 4);
    sizer_4->Add(m_textDescription, 4, wxLEFT|wxRIGHT|wxEXPAND, 4);
    sizer_2->Add(sizer_4, 0, wxTOP|wxBOTTOM|wxEXPAND, 4);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 4);
    sizer_5->Add(button_1, 0, 0, 0);
    sizer_5->Add(panel_1, 1, wxEXPAND, 0);
    sizer_5->Add(button_2, 0, 0, 0);
    sizer_1->Add(sizer_5, 0, wxALL|wxEXPAND, 8);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

const wxString TagInputDialog::Title() const
{
    return m_textTitle->GetValue();
}

const wxString TagInputDialog::Description() const
{
    return m_textDescription->GetValue();
}
