// -*- C++ -*- generated by wxGlade 0.6.3 on Thu Dec 08 14:28:26 2011

#include "DBAccess.h"

#include "ClientDataExportDialog.h"

// begin wxGlade: ::extracode
// end wxGlade

const wxString ClientDataExportDialog::TITLE    =   wxT("Client Data Export");

ClientDataExportDialog::ClientDataExportDialog(CDBAccess* dbaccess, wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxMINIMIZE_BOX)
, _objDBAccess(dbaccess)
{
    // begin wxGlade: ClientDataExportDialog::ClientDataExportDialog
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Options"));
    static_line_1 = new wxStaticLine(this, wxID_ANY);
    radioAll = new wxRadioButton(this, 1000, wxT("All Words"));
    radioDate = new wxRadioButton(this, 1001, wxT("By Date"));
    checkLess = new wxCheckBox(this, 1002, wxT("Less than"));
    dateLess = new wxDatePickerCtrl(this, wxID_ANY, wxDefaultDateTime, wxDefaultPosition, wxDefaultSize, wxDP_DROPDOWN);
    checkGreater = new wxCheckBox(this, 1004, wxT("Greater than"));
    dateGreater = new wxDatePickerCtrl(this, wxID_ANY, wxDefaultDateTime, wxDefaultPosition, wxDefaultSize, wxDP_DROPDOWN);
    radioTag = new wxRadioButton(this, 1005, wxT("By Tag"));
    label_4 = new wxStaticText(this, wxID_ANY, wxT("Title"));
    const wxString *listTag_choices = NULL;
    listTag = new wxComboBox(this, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, listTag_choices, wxCB_DROPDOWN|wxCB_DROPDOWN|wxCB_READONLY|wxCB_SORT);
    label_1_copy = new wxStaticText(this, wxID_ANY, wxT("Export"));
    static_line_1_copy = new wxStaticLine(this, wxID_ANY);
    label_5 = new wxStaticText(this, wxID_ANY, wxT("Output File"));
    editOutput = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    btnBrowse = new wxButton(this, 1006, wxT("&Browse.."));
    static_line_2 = new wxStaticLine(this, wxID_ANY);
    btnExport = new wxButton(this, 1008, wxT("&Export"));
    panel_1 = new wxPanel(this, wxID_ANY);
    btnClose = new wxButton(this, wxID_CLOSE, wxEmptyString);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(ClientDataExportDialog, wxDialog)
    // begin wxGlade: ClientDataExportDialog::event_table
    EVT_RADIOBUTTON(1000, ClientDataExportDialog::OnRadioAllClick)
    EVT_RADIOBUTTON(1001, ClientDataExportDialog::OnRadioDateClick)
    EVT_CHECKBOX(1002, ClientDataExportDialog::OnCheckLessClick)
    EVT_CHECKBOX(1004, ClientDataExportDialog::OnCheckGreaterClick)
    EVT_RADIOBUTTON(1005, ClientDataExportDialog::OnRadioTagClick)
    EVT_BUTTON(1006, ClientDataExportDialog::OnBtnBrowseClick)
    EVT_BUTTON(1008, ClientDataExportDialog::OnBtnExportClick)
    EVT_BUTTON(wxID_CLOSE, ClientDataExportDialog::OnBtnCloseClick)
    // end wxGlade
END_EVENT_TABLE();


void ClientDataExportDialog::OnRadioAllClick(wxCommandEvent &event)
{
    checkLess->Enable(false);
    checkGreater->Enable(false);
    dateLess->Enable(false);
    dateGreater->Enable(false);

    label_4->Enable(false);
    listTag->Enable(false);

}


void ClientDataExportDialog::OnRadioDateClick(wxCommandEvent &event)
{
    checkLess->Enable(true);
    checkGreater->Enable(true);
    dateLess->Enable(true);
    dateGreater->Enable(true);

    label_4->Enable(false);
    listTag->Enable(false);
}


void ClientDataExportDialog::OnCheckLessClick(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (ClientDataExportDialog::OnCheckLessClick) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void ClientDataExportDialog::OnCheckGreaterClick(wxCommandEvent &event)
{
    event.Skip();
    wxLogDebug(wxT("Event handler (ClientDataExportDialog::OnCheckGreaterClick) not implemented yet")); //notify the user that he hasn't implemented the event handler yet
}


void ClientDataExportDialog::OnRadioTagClick(wxCommandEvent &event)
{
    checkLess->Enable(false);
    checkGreater->Enable(false);
    dateLess->Enable(false);
    dateGreater->Enable(false);

    label_4->Enable(true);
    listTag->Enable(true);
}


void ClientDataExportDialog::OnBtnBrowseClick(wxCommandEvent &event)
{
    wxFileDialog dlg(this, wxT("Select output file"), wxEmptyString, wxT("LingosHook_clientdata.db3"), wxT("SQLite3 Files(*.db3)|*.db3|All Files(*.*)|*.*"));
    if(dlg.ShowModal() == wxID_OK)
    {
        editOutput->SetValue(dlg.GetPath());
    }
}


void ClientDataExportDialog::OnBtnCloseClick(wxCommandEvent &event)
{
    Close();
}

void ClientDataExportDialog::OnBtnExportClick(wxCommandEvent &event)
{
    btnClose->Enable(false);

    if(Export() == 0)
    {
        wxMessageBox(wxT("Export Complete."), TITLE, wxCENTRE | wxOK | wxICON_INFORMATION);
    }
    else
    {
        wxMessageBox(wxT("Export FAIL."), TITLE, wxCENTRE | wxOK | wxICON_ERROR);
    }

    btnClose->Enable(true);
}

// wxGlade: add ClientDataExportDialog event handlers


void ClientDataExportDialog::set_properties()
{
    // begin wxGlade: ClientDataExportDialog::set_properties
    SetTitle(wxT("Client Data Export"));
    SetSize(wxSize(286, 320));
    label_1->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    checkLess->Enable(false);
    dateLess->Enable(false);
    checkGreater->Enable(false);
    dateGreater->Enable(false);
    label_4->Enable(false);
    listTag->Enable(false);
    label_1_copy->SetFont(wxFont(10, wxDEFAULT, wxNORMAL, wxBOLD, 0, wxT("")));
    // end wxGlade
}


void ClientDataExportDialog::do_layout()
{
    // begin wxGlade: ClientDataExportDialog::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2_copy = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_2->Add(label_1, 0, wxEXPAND, 0);
    sizer_2->Add(static_line_1, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_1->Add(sizer_2, 0, wxALL|wxEXPAND, 8);
    sizer_3->Add(radioAll, 0, wxTOP|wxBOTTOM|wxEXPAND, 4);
    sizer_1->Add(sizer_3, 0, wxLEFT|wxEXPAND, 24);
    sizer_4->Add(radioDate, 0, wxTOP|wxBOTTOM|wxEXPAND, 4);
    sizer_5->Add(checkLess, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_5->Add(dateLess, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_4->Add(sizer_5, 0, wxLEFT|wxEXPAND, 24);
    sizer_6->Add(checkGreater, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_6->Add(dateGreater, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_4->Add(sizer_6, 0, wxLEFT|wxEXPAND, 24);
    sizer_1->Add(sizer_4, 0, wxLEFT|wxEXPAND, 24);
    sizer_7->Add(radioTag, 0, wxTOP|wxBOTTOM|wxEXPAND, 4);
    sizer_8->Add(label_4, 0, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_8->Add(listTag, 0, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_7->Add(sizer_8, 1, wxLEFT|wxEXPAND, 24);
    sizer_1->Add(sizer_7, 0, wxLEFT|wxEXPAND, 24);
    sizer_2_copy->Add(label_1_copy, 0, wxEXPAND, 0);
    sizer_2_copy->Add(static_line_1_copy, 1, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_1->Add(sizer_2_copy, 0, wxALL|wxEXPAND, 8);
    sizer_9->Add(label_5, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_9->Add(editOutput, 1, wxALL|wxEXPAND|wxALIGN_CENTER_VERTICAL, 4);
    sizer_9->Add(btnBrowse, 0, wxALL|wxALIGN_CENTER_VERTICAL, 4);
    sizer_1->Add(sizer_9, 0, wxLEFT|wxEXPAND, 24);
    sizer_1->Add(static_line_2, 0, wxALL|wxEXPAND, 4);
    sizer_10->Add(btnExport, 0, wxALL, 4);
    sizer_10->Add(panel_1, 1, wxEXPAND, 0);
    sizer_10->Add(btnClose, 0, wxALL, 4);
    sizer_1->Add(sizer_10, 0, wxEXPAND, 0);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

int ClientDataExportDialog::Export()
{
    wxString sql;
    if(MakeSQL(sql) != 0)
        return -1;

    wxString file = editOutput->GetValue();
    wxString::size_type pos = file.find_last_of(wxT("."));
    if(pos == wxString::npos)
    {
        file = file + wxT(".db3");
    }

    wxSQLite3Database db;
    if(OpenDB(file, db) != 0)
        return -1;

    if(TransDB(db, sql) != 0)
        return -1;

    CloseDB(db);

    return 0;
}

int ClientDataExportDialog::MakeSQL(wxString &sql)
{
//select WordTable.SrcID, WordTable.Word, SrcDataTable.HTML, SrcDataTable.CheckinTime from WordTable, SrcDataTable where WordTable.SrcID = SrcDataTable.SrcID
// and SrcDataTable.CheckinTime > '2011-08-17 12:14:52'
    sql = wxT("select WordTable.SrcID, WordTable.Word, SrcDataTable.HTML from WordTable, SrcDataTable");
    if(radioAll->GetValue())
    {
    }
    else if(radioDate->GetValue())
    {
        wxString cond;
        if(checkLess->IsChecked())
        {
            cond = wxT(", W where 
        }
        else if(checkGreater->IsChecked())
        {
        }
        else if(checkLess->IsChecked() && checkGreater->IsChecked())
        {
        }
    }
    else if(radioTag->GetValue())
    {
    }
    else
    {
        return -1;
    }
    return 0;
}